package org.fourstack.interview.hackerrank;

public class CharInRepeatedString {
	
	/**
	 * Method to find the number of occurrence of given character in a String, which
	 * is created by repeating n times for the length of range.
	 * 
	 * @param str   Input String which is used to generate the Repeated String.
	 * @param ch    Character which is repeated n number of times.
	 * @param range The total length of String, which is generated by repeating the
	 *              input String.
	 * @return Number of times the character occurred in String.
	 */
	public static int repeatedCharCount(String str, char ch, int range) {

		// Step 1: Check how many times the complete String is repeated for Range
		int completeOccurrence = range / str.length();

		// Step 2: Get the remaining String length in range.
		int remainingStrLen = range % str.length();

		// Step 3: Get count of character occurrence in String
		int charCount = getCharCount(str, ch);

		/*
		 * FORMULA = ( charCount * completeOccurrence ) + number of occurrence of
		 * Character in remaining String
		 */

		int totalOccurrenceCount = (charCount * completeOccurrence)
				+ getCharCount(str.substring(0, remainingStrLen), ch);

		return totalOccurrenceCount;
	}

	private static int getCharCount(String str, char ch) {
		int count = 0;
		for (char c : str.toCharArray())
			if (ch == c)
				count++;

		return count;
	}

}
